name: dq_engine_dbt
version: "1.0"
config-version: 2

profile: dq_engine_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dq_engine_dbt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
